In [1]:
# importqamos las librerias necesarias
import numpy as np

# Descomposición de matrices por medio de sus Eigenvelores y Eigenvectores

Una matriz A, se puede descomponer a partir de sus eigenvalores y eigenvectores de la siguienten manera:

$$
A=VLV^{-1}=
\begin{bmatrix}
|    & |   &        & |   \\
u_1  & u_2 & \cdots & u_n \\
|    & |   &        & |
\end{bmatrix}
\,
\begin{bmatrix}
\lambda_1 &           &        &  \\
          & \lambda_2 &        &  \\
          &           & \ddots &  \\
          &           &        & \lambda_n
\end{bmatrix}
\,
\begin{bmatrix}
|    & |   &        & |   \\
u_1  & u_2 & \cdots & u_n \\
|    & |   &        & |
\end{bmatrix}^{\,\, -1}
$$

Donde:
- $V$ es la matriz de eigenvectores
- $L$ es la matriz diagonal con los eigenvalores como sus elementos
- $\lambda$ son los eigenvalores
- $u_i$ es el i-ésimo eigenvector.

Para los casos en los que resulta que nuestra matriz $A$ es simetrica, no sera necesario calcular la inversa de $V$, sino su transpuesta, $A^{T}$, es decir:
$$A_{sim} = VLV^{T}$$

## Caso 1: Matriz no simetrica

In [2]:
# Veamos un ejemplo, empezando por definir nuestra matriz de ejemplo
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
# Calculemos los eigenvalores y los eigenvectores de A
evals, evecs = np.linalg.eig(A)
print(evals)
print(10*"-")
print(evecs)

[ 5. -1.]
----------
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [4]:
# veamos si al realizar la operacion VLV volvemos a la matriz original
Acalc = evecs.dot(np.diag(evals)).dot(np.linalg.inv(evecs))
print(Acalc)

[[3. 2.]
 [4. 1.]]


## Caso 2: Matriz simetrica

In [9]:
# Definamos una matriz simetrica 2x2
B = np.array([[6,7],[7,6]])
print(B)

[[6 7]
 [7 6]]


In [10]:
# Calculemos los eigenvalores y los eigenvectores de B
evals, evecs = np.linalg.eig(B)
print(evals)
print(10*"-")
print(evecs)

[13. -1.]
----------
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [11]:
# Calculemos B a partir de sus eigenelementos
Bcalc = evecs.dot(np.diag(evals)).dot(evecs.T)
print(Bcalc)

[[6. 7.]
 [7. 6.]]
