In [3]:
# importamos librerias necesarias
import numpy as np

# Descomponer una matriz no cuadrada - metodo SVD

El metodo SVD significa Descomposicion de valores singulares o Singular Value Decomposition por sus siglas en ingles.

In [34]:
# Definamos una matriz no cuadrada
A = np.array([[1,2,3],[4,7,1]])
print(A)

[[1 2 3]
 [4 7 1]]


In [35]:
# calculemos sus valores singulares
U, S, V = np.linalg.svd(A)
print(U)
print(10*"*")
print(S)
print(10*"*")
print(V)

[[-0.33321076  0.94285237]
 [-0.94285237 -0.33321076]]
**********
[8.56863758 2.56484894]
**********
[[-0.47902834 -0.84802141 -0.22669702]
 [-0.1520521  -0.17418982  0.97290188]
 [-0.86452993  0.50051733 -0.04550158]]


Para volver a la matriz original, a apartir de las matrices de los elementos singulares, debemos realizar la siguiente operacion:

$$A = USV$$

Donde:
- $U$ es la matriz que asignamos como `U`
- $V$ es la matriz que asignamos como `V`
- $S$ es una matris diagonal con los elementos de `S` en su diagonal.

Notese
> La matriz resultante de `S` conincide con la dimensiones de `V` para ejecutar una multiplicacion correcta entre estas 2 matrices. Lo que debemos hacer es agregar columnas de 0's hasta que las dimensiones no generen errores.

In [40]:
%run "./funciones_auxiliares/agregarCeros.ipynb"

# ajustando S a forma matricial
S = np.diag(S)

S = agregarColumnasDeCeros(S,1)

print(S)

[[8.56863758 0.         0.        ]
 [0.         2.56484894 0.        ]]


In [41]:
Acalc = U.dot(S).dot(V)
print(A)

[[1 2 3]
 [4 7 1]]


# Borrador de ideas

In [21]:
# matriz
C = np.array([[3,0],[4,5]])
print(C)

[[3 0]
 [4 5]]


In [30]:
%run "./funciones_auxiliares/agregarCeros.ipynb"

In [33]:
C2 = agregarColumnasDeCeros(C,3)
print(C2)

C3 = agregarFilasDeCeros(C2,3)
print(C3)

[[3. 0. 0. 0. 0.]
 [4. 5. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [4. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
U, S, V = np.linalg.svd(C)
print(U)
print(10*"*")
print(S)
print(10*"*")
print(V)

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
**********
[6.70820393 2.23606798]
**********
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [18]:
Ccalc = U.dot(np.diag(S)).dot(V)
print(Ccalc)

[[3.00000000e+00 1.33226763e-15]
 [4.00000000e+00 5.00000000e+00]]


In [20]:
A.shape

(2, 3)