In [1]:
import numpy as np

np.set_printoptions(suppress=True)

# Pseudoinversa de una matriz
La pseudo inversa de Moore Penrose es utilizada cuando en un sistema de ecuaciones lineales representado por $Ax = B$, $x$ no tiene inversa.
La pseudo inversa de MP es única y existe si se verifican 4 condiciones.

Para calcularla se siguen los siguientes pasos:
- Calcular las matrices $U$, $D$, y $V$ (matrices SVD) de $A$.
- Construir $D_{pse}$: una matriz de ceros que tiene igual dimension de $A$, y que luego se transpone.
- Reemplazar la submatriz `D_pse[: D.shape[0], : D.shape[0]]` por `np.linalg.inv(np.diag(D))`
- Reconstruir pseudoinversa: `A_pse = V.T.dot(D_pse).dot(U.T)`

Para calcularla automaticamente por Python: `np.linalg.pinv(A)`
Lo que obtenemos con `A_pse` es una matriz muy cercana a la inversa. Cercano en el sentido de que minimiza la norma dos de estas distancias. O sea, de estos errores que estamos cometiendo.
`A_pse` no es conmutativa, es decir, `A_pse·A ≠ A·A_pse`

## Calculamos SVD a la matriz A

In [2]:
# Definimos matriz
A = np.array([[2,3], [5,7], [11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [5]:
# Calculamos su SVD
U, D, V = np.linalg.svd(A)
D = np.diag(D)
print("U")
print(U)
print("\nD")
print(D)
print("\nV")
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]

D
[[19.40321383  0.        ]
 [ 0.          0.71783924]]

V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


## Calculamos $D_{inv}$

In [7]:
# Dimensiones que debe tener la pseudoinversa
print("Dimensiones de la pseudoinversa")
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

Dimensiones de la pseudoinversa
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Valores que vamos a remplazar en D_pse
print("Valores a ser remplazados en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a ser remplazados en D_pse
[[0. 0.]
 [0. 0.]]


In [10]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(D))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [13]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(D)
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


## Calculamos la pseudoinversa de A

In [14]:
# Finalmente, calculamos la pseudoinversa de A usando las matrices U, D y V
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [15]:
# Python ya calcula tiene un metodo para calcular la pseudoinversa usando SVD
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


## Comprobamos multiplicando A_pse $\times$ A

In [16]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


# $A_{pse}$ no es conmutativa
A diferencia la inversa original, las pseudoinversas no son conmutativas

In [17]:
print(A.dot(A_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


# Existen otros metodos para calcular las pseudoinversas

In [19]:
## Otros metodos para calcular inversas
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
